version: "3.9"

services:
  postgres:
    image: postgres:18-alpine
    container_name: easm-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-easm_db}
      - POSTGRES_USER=${POSTGRES_USER:-easm_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-easm_password}
    ports:
      - "${POSTGRES_LOCAL_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-easm_user} -d ${POSTGRES_DB:-easm_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: easm-redis
    ports:
      - "${REDIS_LOCAL_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:8-jammy
    container_name: easm-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB:-easm_mongo}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./src/backend
    container_name: easm-api
    command: sh /app/start-api.sh
    volumes:
      - ./src/backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "${API_LOCAL_PORT:-8000}:8000"
    env_file:
      - skaffold.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=${MONGO_DB:-easm_mongo}
      - GUNICORN_WORKERS=4
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  static_volume:
