# Generated by Django for scanner app
# This app uses MongoDB with pymongo, so no database migrations are needed

from django.db import migrations


class Migration(migrations.Migration):
    """Initial migration for scanner app - no operations needed as we use MongoDB."""

    initial = True

    dependencies = []

    operations = []
