{{- if and .Values.easmApi.enabled (ne (.Values.easmApi.enabled | toString) "False") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "easm-api.fullname" . }}
  labels:
    {{- include "easm-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.secretKey | quote }}
  {{- if and .Values.postgresql.enabled (ne (.Values.postgresql.enabled | toString) "False") }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  {{- end }}
{{- end }}
