apiVersion: v1
kind: Secret
metadata:
  name: {{ include "easm-api.fullname" . }}
  labels:
    {{- include "easm-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.secretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
