{{- if and .Values.easmApi.enabled (ne (.Values.easmApi.enabled | toString) "False") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "easm-api.fullname" . }}
  labels:
    {{- include "easm-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "easm-api.selectorLabels" . | nindent 4 }}
{{- end }}
